### PR TITLE
Support large files in cwaitfor by using 64-bit integers

### PR DESCRIPTION
**Pull request by SamuelTrahanNOAA**
The tracker's waitfor cannot handle files 2GB or larger because it uses 32-bit integers to measure the file size. This changes the integers to 64 bits.

Fix hafs-community/HAFS/issues/215

### CODE REVIEW

**Review by BijuThomas-NOAA — DISMISSED** [review]

**Comment by BijuThomas-NOAA** [comment]
@SamuelTrahanNOAA ,
TimMarchok-NOAA reported to us the following build warning during compilation with the proposed 64-bit integers fixes changes.

```
/mnt/lfs4/HFIP/hwrfv3/Biju.Thomas/sorc_gettrk.fd/gettrk.fd/module_waitfor.f(19): warning #6075: The data type of the actual argument does not match the definition.
     &len_trim(command)+1,retval)
-----------------------^
/mnt/lfs4/HFIP/hwrfv3/Biju.Thomas/sorc_gettrk.fd/gettrk.fd/module_waitfor.f(71): warning #6075: The data type of the actual argument does not match the definition.   [LEN_TRIM]
     &      ,maxwait_in,sleeptime_in,trim(filename),len_trim(filename))
```
Noticed that an integer type mismatch (kind=4 and  kind=8) of the string length exists between the subroutines waitfor_helper and run_cmd_helper, and their corresponding call statements.
I made a few changes in module_waitfor.f (Jet: /mnt/lfs4/HFIP/hwrfv3/Biju.Thomas/sorc_gettrk.fd/gettrk.fd) to fix the build warning. If you agree, please update the bi-waitfor branch with the new module_waitfor.f.

Thanks

**Comment by SamuelTrahanNOAA** [comment]
There are hundreds of changes, not just changes in module_waitfor.f. I think this was based on a different branch. You deleted the `.git` directory, so I don't know what the changes were. Can you give me a diff, or branch, or at least a directory that still has the `.git` information?

**Comment by BijuThomas-NOAA** [comment]
@SamuelTrahanNOAA It is here:

/mnt/lfs4/HFIP/hwrfv3/Biju.Thomas/big-waitfor/src/gettrk.fd

**Comment by SamuelTrahanNOAA** [comment]
I have merged your change.

```diff
diff --git a/src/gettrk.fd/module_waitfor.f b/src/gettrk.fd/module_waitfor.f
index b775839..93d7d5f 100644
--- a/src/gettrk.fd/module_waitfor.f
+++ b/src/gettrk.fd/module_waitfor.f
@@ -21,7 +21,7 @@
 
         subroutine run_cmd_helper(cmd,cmdlen,retval)
           implicit none
-          integer(kind=8), intent(in) :: cmdlen
+          integer, intent(in) :: cmdlen
           integer(kind=8), intent(out) :: retval
           character(*), intent(in) :: cmd(cmdlen)
 
@@ -74,7 +74,8 @@
         subroutine waitfor_helper(status,minage,minsize
      &        ,maxwait,sleeptime,filename,N)
           integer(kind=8), intent(in) :: minage,minsize,maxwait
-          integer(kind=8), intent(in) :: sleeptime,N
+          integer(kind=8), intent(in) :: sleeptime
+          integer, intent(in) :: N
           character(len=N),intent(in) :: filename
           integer(kind=8), intent(out) :: status
 
```

**Comment by TimMarchok-NOAA** [comment]
I reviewed Sam's latest changes that are referenced in this pull request, I tested his new code, and all is good.  I approve the PR.

**Comment by TimMarchok-NOAA** [comment]
I reviewed these changes from Sam that are referenced in this pull request, and all looks good and the results matched as expected with the previous version of the code.  I approve this PR.

**Comment by SamuelTrahanNOAA** [comment]
@TimMarchok-NOAA - You closed the PR without merging it. If you do approve, you should merge it.

**Comment by TimMarchok-NOAA** [comment]
Approved.

**Comment by SamuelTrahanNOAA** [comment]
@TimMarchok-NOAA - you didn't actually approve the changes. You need to do a review and select "approve" among the three options (comment, review, request changes).

**Comment by TimMarchok-NOAA** [comment]
Hi Sam.  When I go to review the changes, I'm now seeing a lot of changes in all 4 routines.  However, with this very latest tweak, I know that you only made a couple small changes to module_waitfor.f.  Are all these changes showing because the review panel is also showing the original changes you made to all 4 routines back in August, and those hadn't been merged yet?

**Comment by SamuelTrahanNOAA** [comment]
This pull request is only for my changes back in August. They were never merged to the support/HAFS branch, so you still see the changes.

**Review by TimMarchok-NOAA — APPROVED** [review]
I've tested these changes.  All is good.  Approved.

**Review by BijuThomas-NOAA — APPROVED** [review]

**Review by BinLiu-NOAA — APPROVED** [review]
Thanks for enabling large file support in cwaitfor for the tracker!

**Comment by SamuelTrahanNOAA** [comment]
I look forward to seeing this merged. I'll be able to remove my personal tracker fork from the Atmospheric River fork of HAFS.

**Pull request merged**
